import {
  defineComponent,
  defineEvent,
  defineResource
} from "nexusengine/ecs";

export const Components = Object.freeze({
  Identity: defineComponent("battle-clash.identity"),
  Position: defineComponent("battle-clash.position"),
  Faction: defineComponent("battle-clash.faction"),
  Renderable: defineComponent("battle-clash.renderable"),
  Health: defineComponent("battle-clash.health"),
  Attack: defineComponent("battle-clash.attack"),
  Targeting: defineComponent("battle-clash.targeting"),
  Movement: defineComponent("battle-clash.movement"),
  Footprint: defineComponent("battle-clash.footprint"),
  Troop: defineComponent("battle-clash.troop"),
  Building: defineComponent("battle-clash.building"),
  Defense: defineComponent("battle-clash.defense"),
  Hero: defineComponent("battle-clash.hero"),
  HeroCombat: defineComponent("battle-clash.hero-combat"),
  TerritoryMarker: defineComponent("battle-clash.territory-marker"),
  FrontMarker: defineComponent("battle-clash.front-marker"),
  ResourceNode: defineComponent("battle-clash.resource-node")
});

export const Resources = Object.freeze({
  RaidState: defineResource("battle-clash.raid-state"),
  DeploymentState: defineResource("battle-clash.deployment-state"),
  CommandQueue: defineResource("battle-clash.command-queue"),
  EffectsState: defineResource("battle-clash.effects-state"),
  BattleMetadata: defineResource("battle-clash.metadata"),
  ProgressionState: defineResource("battle-clash.progression-state"),
  DefenseState: defineResource("battle-clash.defense-state"),
  SessionState: defineResource("battle-clash.session-state"),
  SceneState: defineResource("battle-clash.scene-state"),
  WorldState: defineResource("battle-clash.world-state"),
  HeroState: defineResource("battle-clash.hero-state"),
  TerritoryState: defineResource("battle-clash.territory-state"),
  ArmyState: defineResource("battle-clash.army-state"),
  EconomyState: defineResource("battle-clash.economy-state"),
  LandscapeState: defineResource("battle-clash.landscape-state"),
  SanctumState: defineResource("battle-clash.sanctum-state"),
  ObjectiveState: defineResource("battle-clash.objective-state"),
  RoomState: defineResource("battle-clash.room-state"),
  LootState: defineResource("battle-clash.loot-state"),
  AccountState: defineResource("battle-clash.account-state"),
  AbilityState: defineResource("battle-clash.ability-state"),
  PlayerState: defineResource("battle-clash.player-state"),
  PlayerObservation: defineResource("battle-clash.player-observation"),
  PlayerMemory: defineResource("battle-clash.player-memory"),
  PlayerDecision: defineResource("battle-clash.player-decision"),
  PlayerEpisode: defineResource("battle-clash.player-episode"),
  PlayerLearningSignal: defineResource("battle-clash.player-learning-signal")
});

export const Events = Object.freeze({
  DeploymentAccepted: defineEvent("battle-clash.deployment.accepted"),
  DeploymentRejected: defineEvent("battle-clash.deployment.rejected"),
  TargetAcquired: defineEvent("battle-clash.target.acquired"),
  AttackResolved: defineEvent("battle-clash.attack.resolved"),
  EntityDestroyed: defineEvent("battle-clash.entity.destroyed"),
  RaidStarted: defineEvent("battle-clash.raid.started"),
  RaidCompleted: defineEvent("battle-clash.raid.completed"),
  RaidReset: defineEvent("battle-clash.raid.reset"),
  ProgressionAwarded: defineEvent("battle-clash.progression.awarded"),
  LevelGained: defineEvent("battle-clash.progression.level-gained"),
  DefenseFortified: defineEvent("battle-clash.defense.fortified"),
  SessionChanged: defineEvent("battle-clash.session.changed"),
  SceneChanged: defineEvent("battle-clash.scene.changed"),
  HeroMoved: defineEvent("battle-clash.hero.moved"),
  TerritoryDiscovered: defineEvent("battle-clash.territory.discovered"),
  TerritoryEntered: defineEvent("battle-clash.territory.entered"),
  TerritoryClaimed: defineEvent("battle-clash.territory.claimed"),
  FrontChanged: defineEvent("battle-clash.front.changed"),
  EconomyTicked: defineEvent("battle-clash.economy.ticked"),
  LandmarkInteracted: defineEvent("battle-clash.landmark.interacted"),
  LandscapeChanged: defineEvent("battle-clash.landscape.changed"),
  ObjectiveProgressed: defineEvent("battle-clash.objective.progressed"),
  ObjectiveCompleted: defineEvent("battle-clash.objective.completed"),
  RoomChanged: defineEvent("battle-clash.room.changed"),
  AccountChanged: defineEvent("battle-clash.account.changed"),
  AbilityUsed: defineEvent("battle-clash.ability.used"),
  PlayerObserved: defineEvent("battle-clash.player.observed"),
  PlayerMemoryStored: defineEvent("battle-clash.player.memory-stored"),
  PlayerMemoryRetrieved: defineEvent("battle-clash.player.memory-retrieved"),
  PlayerDecisionMade: defineEvent("battle-clash.player.decision-made"),
  PlayerActionAccepted: defineEvent("battle-clash.player.action-accepted"),
  PlayerActionRejected: defineEvent("battle-clash.player.action-rejected"),
  PlayerOutcomeRecorded: defineEvent("battle-clash.player.outcome-recorded"),
  PlayerEpisodeStarted: defineEvent("battle-clash.player.episode-started"),
  PlayerEpisodeCompleted: defineEvent("battle-clash.player.episode-completed"),
  PlayerEpisodeFailed: defineEvent("battle-clash.player.episode-failed"),
  PlayerSkillPromoted: defineEvent("battle-clash.player.skill-promoted")
});
